language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
os:
  - linux
env:
  - BUILD_LEADER_ID=2
jobs:
  include:
    - stage: npm release
      node_js: "8"
      os: "linux"
      script: echo "Deploying to npm ..."
      before_script:
        - npm prune
      after_success:
        - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
